#!/bin/sh

get_packages() {
  script_dir="$(realpath "$(dirname "$0")")"
  cat "$script_dir/../packages.txt"
}

install_packages() {
  # shellcheck disable=SC2046
  echo apk add $(get_packages)
}

configure_post_install() {
  rc-update add docker boot &&
    service docker start
}

apk update &&
  install_packages &&
  configure_post_install
